version: '3.5'

services:
    backend-flask:
        container_name: backend-flask
        build:
            context: ./Dockerfiles/backend-flask/
            dockerfile: Dockerfile
        links:
            - db
        ports:
            - "5000:5000"
    db:
        image: mysql:5.7
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: r00tp4ss
        volumes:
            - ./Dockerfiles/db:/docker-entrypoint-initdb.d/:ro
    user-interface:
        container_name: user-interface
        build:
            context: ./Dockerfiles/user-interface/
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
